# This is a basic workflow to help you get started with Actions

name: CI CD

# Controls when the action will run. 
on: push
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a single job called "test"
  test: 
  
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Test the code
        run: python helloworld.py
        
  build:
    runs-on: ubuntu-latest
    needs: test
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: create the artifact
        uses: actions/upload-artifact@v2
